[workspace]
authors = ["MVPavan <mvpavan42@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojos"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025122805,<0.27"
numpy = ">=2.4.1,<3"
pillow = ">=12.1.0,<13"
py-opencv = ">=4.13.0,<5"
max = ">=26.2.0.dev2026013005,<27"
